title:              BELLSTONE
email:              pjongsuk1@gmail.com
# description:        A Blog Theme by Start Bootstrap
author:             BELLSTONE
baseurl:            ""
url:                "https://park-jongseok.github.io"

# Social Profiles
# twitter_username:   SBootstrap
github_username:    PARK-JONGSEOK
# facebook_username:  StartBootstrap
# linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-137799696-2 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
